#CRIAÇÃO DO TIPO CONJUNTO (SET)
C1 ={1,3,4,5,8,100,100,100}
#SEMPRE COLOCARA EM ORDEM OS ELEMENTOS
#ELEMEMNTOS UNICOS, SE O MEMSO SE REPETIR ELE AOPENA SERÁ MOSTRADA UMA UNICA VEZ
print(C1)

print("#OPERAÇÕES COM CONJUNTOS: UNIÃO DE CONJUNTOS")
#OPERAÇÕES COM CONJUNTOS: UNIÃO DE CONJUNTOS
A={1,0,4,5,7,8,}
B={1,4,10,2,4,}
print(A|B) #'|' REPRESENTA UNIÃO
print(A.union(B)) #'METODO UNION' REPRESENTA UNIÃO

print('#OPERAÇÕES COM CONJUNTOS: INTERCESSÃO DE CONJUNTOS')
#OPERAÇÕES COM CONJUNTOS: INTERCESSÃO DE CONJUNTOS
A={1,0,4,5,7,8,}
B={1,4,10,2,4,}
print(A&B) #'&' REPRESENTA INTERCESSÃO
print(A.intersection(B)) #'METODO INTERSERTION' REPRESENTA INTERCESSÃO

print('#OPERAÇÕES COM CONJUNTOS: DIFERENÇA DE CONJUNTOS')
#OPERAÇÕES COM CONJUNTOS: DIFERENÇA DE CONJUNTOS
A={1,0,4,5,7,8,}
B={1,4,10,2,4,}
print(A-B) #'&' REPRESENTA DIFERENÇA QUEM TEM EM UM QUE NÃO TEM NO OUTRO
print(A.difference(B)) #'METODO DIFERENÇA' REPRESENTA DIFERENÇA


#METODOS DO  USADOS EM SET (CONJUNTO)
#SE APLICA OS METODOS DE LISTA TAMBÉM CONSULTAR MATERIA DA AULA LIST
B1={1,2,3,4,5,6}
B2={1,2,}
B3={88,67,44,}

#ADD UM ELEMENTO AO CONJUNTO
B1.add(7)#ADD O ELEMENTO 
print(B1)

#ATUALIZO OS ELEMENTO DO CONJUNTO
B1.update([0,10,15,33])#ATUALIZANDO DESCONSIDERAANDO  OS ELEMENTOS JÁ EXISTENTES 
print(B1)

#DESCARTAR O ELEMENTO DO CONJUNTO
B1.discard(3)#REMOVE O ELEMENTO MAS NÃO GERAR ERRO CASO ELE NÃO EXISTA, DIFERENTE DO .REMOVE 
print(B1)

#DJUNTOS UM DO OUTRO
#SE NÃO TEM ELEMENTO SEMELHANTES ENTRE SI
print(B1.isdisjoint(B2))#NÃO POSSUI ELEMENTOS DIFERENTES
print(B1.isdisjoint(B3))#POSSUI

#SUBCONJUNTOS
print(B1.issubset(B2))#E SUB
print(B2.issubset(B1))#N É SUB

#CONTEM 
print(B1.issuperset(B2))#CONTÉM
print(B2.issuperset(B1))#N CONTÉM

print("#USO PRÁTICO DOS CONJUNTOS")
#USO PRÁTICO DOS CONJUNTOS
ING={'PAULO','JULIA','MARLON','GABREL','ANNY', 'GUI', 'OLIVIA'}
FRC={'VITOR','JULIA','MARLON','MARIA','INACIO', 'FRANÇA', 'BARBARA'}
SPN={'VITOR','HIGOR','KATIA','MARIA','JOSÉ', 'FRANÇA', 'BARBARA',"YANNE"}

#ORDENAR OS ALUNOS MATRICULADOS
TODOS= ING|FRC|SPN
print (f"TODOS OS ALUNOS MATRICULADOS NOS CURSO DE IDIOMAS {TODOS}")
#QUANTOS ALUNO SESTÃO EM PELOMENOS 2 CURSOS
DESCONTO=(ING&FRC)|(ING&SPN)|(SPN&FRC)
print(DESCONTO)
print (f"TODOS OS ALUNOS MATRICULADOS QUE TERÁ DESCONTO {DESCONTO}")
