#CRIAÇÃO DO TIPO TUPLA

#HETEROGENIA
v1=('a','u', False, True, 33,55)
print(v1)

#HOMOGENIA
v2=('a','u', 'False', 'True', '33','55')
print(v2)

#TODAS AS FUNCIONALIDADES DA LISTA SE APLICA AQUI TAMBÉM CONSULTA  DOCUMENTAÇÃO AULA ANTERIOR!
#COM EXCESÃO DAS OPERAÇÃOE SQUE ENVOLVE MUDANÇA DE VALOR, ESSAS NÃO SE APLICA A TUPLE POR SER UM ESTRUTURA IMUTAVEL.